defmodule FlorinaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :florina

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # `secure: true` (HTTPS-only cookie) is enabled in production via
  # `config :florina, :session_secure, true`; left off in dev/test where there's
  # no TLS on localhost. `http_only` keeps the cookie out of reach of JS.
  @session_options [
    store: :cookie,
    key: "_florina_key",
    signing_salt: "MgpuMbo4",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:florina, :session_secure, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :florina,
    gzip: not code_reloading?,
    only: FlorinaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :florina
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Bound the request body (incl. the raw-body capture used by the webhook
    # signature check) so an unauthenticated POST can't force unbounded buffering.
    length: 1_000_000,
    body_reader: {FlorinaWeb.RawBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FlorinaWeb.Router
end
