host:
  ip: 192.168.132.66
  hostname: florina
  domain: florina.vm.neurony.dev
  email: management@neurony.ro
  environment: development

ssh:
  user: neurony
  port: 22
  ssh_key: ~/.ssh/id_rsa

users:
  master:
    username: MASTER
    ssh_keys:
      - MASTER_SSH_KEY

  deployment:
    username: USER
    ssh_keys:
      - USER_SSH_KEY
      - GITHUB_DEPLOY_SSH_KEY

  operations:
    username: OP_USER
    ssh_keys:
      - OP_SSH_KEY

stack:
  - python

database:
  name: florina_dev
  username: florina_user

runtime:
  gunicorn_workers: 3
  app_port: 8000

services:
  nginx: true
  postgresql: true
  redis: false
  python: true
  gunicorn: true
  celery: false
  nodejs: false
  php: false
  mysql: false
