# Generated by Django 4.2.27 on 2025-12-29 13:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('pipedrive_user_id', models.IntegerField(blank=True, help_text='Pipedrive user ID for CRM sync', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in E.164 format (e.g., +1234567890)', max_length=20, null=True)),
                ('is_sales_agent', models.BooleanField(default=False, help_text='Designates whether this user is a sales agent who receives calls')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRE', 'Pre-Meeting Training'), ('POST', 'Post-Meeting Debrief')], help_text='Pre-meeting or post-meeting call', max_length=20)),
                ('scheduled_offset_minutes', models.IntegerField(help_text='Offset in minutes from meeting time (e.g., -60, -30, 15, 30)')),
                ('external_call_id', models.CharField(blank=True, help_text='External call ID from Twilio or ElevenLabs', max_length=100, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INITIATED', 'Initiated (Dialing)'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed (Answered)'), ('NO_ANSWER', 'No Answer / Busy'), ('FAILED', 'System Failed')], default='SCHEDULED', max_length=20)),
                ('recording_url', models.URLField(blank=True, help_text='URL to the call recording', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Transcript of the call conversation', null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the call was actually executed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Attempt',
                'verbose_name_plural': 'Call Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='External ID from Google Calendar or Pipedrive', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Meeting title', max_length=255)),
                ('customer_name', models.CharField(blank=True, help_text='Name of the customer/client', max_length=255)),
                ('start_time', models.DateTimeField(help_text='Meeting start time')),
                ('end_time', models.DateTimeField(help_text='Meeting end time')),
                ('is_pre_call_completed', models.BooleanField(default=False, help_text='True if pre-meeting call was successfully completed')),
                ('is_post_call_completed', models.BooleanField(default=False, help_text='True if post-meeting call was successfully completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VoicePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this prompt', max_length=100)),
                ('system_prompt', models.TextField(help_text='Instructions for ElevenLabs Agent')),
                ('prompt_type', models.CharField(choices=[('PRE', 'Pre-Meeting Training'), ('POST', 'Post-Meeting Debrief')], default='PRE', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active prompt per type is allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice Prompt',
                'verbose_name_plural': 'Voice Prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='voiceprompt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('prompt_type',), name='unique_active_prompt'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='agent',
            field=models.ForeignKey(help_text='Sales agent associated with this meeting', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='meeting',
            field=models.ForeignKey(help_text='Meeting this call is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='voice.meeting'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text='Associated meeting (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='voice.meeting'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time'], name='voice_meeti_start_t_cb4c96_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['end_time'], name='voice_meeti_end_tim_bae99b_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['external_id'], name='voice_meeti_externa_975f62_idx'),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['meeting', 'phase'], name='voice_calla_meeting_735910_idx'),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['status'], name='voice_calla_status_e6fac9_idx'),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['external_call_id'], name='voice_calla_externa_30b1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='voice_activ_timesta_82492b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['level'], name='voice_activ_level_a6c7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['meeting'], name='voice_activ_meeting_ae0b40_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='voice_activ_user_id_e00bf3_idx'),
        ),
    ]
