# Generated by Django 4.2.27 on 2025-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0002_alter_callattempt_external_call_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceprompt",
            name="first_message",
            field=models.TextField(
                blank=True,
                help_text="First message/greeting for the AI agent (optional). Supports same variables as system prompt.",
                null=True,
            ),
        ),
    ]
