# Generated by Django 4.2.27 on 2026-01-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_callattempt_summary_callattempt_summary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOauthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='OAuth access token (encrypted in production)')),
                ('refresh_token', models.TextField(help_text='OAuth refresh token (encrypted in production)')),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.JSONField(default=list, help_text='List of OAuth scopes granted')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns these credentials', on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google OAuth Credential',
                'verbose_name_plural': 'Google OAuth Credentials',
                'indexes': [models.Index(fields=['user'], name='voice_googl_user_id_7010e9_idx')],
            },
        ),
    ]
