# Generated by Django 4.2.27 on 2026-01-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0008_googlecalendarwatch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='googlecalendarwatch',
            new_name='voice_googl_user_id_c4f399_idx',
            old_name='voice_googlecalendarwatch_user_idx',
        ),
        migrations.RenameIndex(
            model_name='googlecalendarwatch',
            new_name='voice_googl_channel_96d00e_idx',
            old_name='voice_googlecalendarwatch_channel_id_idx',
        ),
        migrations.RenameIndex(
            model_name='googlecalendarwatch',
            new_name='voice_googl_expirat_956fe4_idx',
            old_name='voice_googlecalendarwatch_expiration_idx',
        ),
        migrations.AlterField(
            model_name='googlecalendarwatch',
            name='channel_id',
            field=models.CharField(help_text='Google Calendar channel ID (unique identifier for this watch)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarwatch',
            name='expiration',
            field=models.DateTimeField(help_text='When this watch channel expires (Google sends expiration notifications)'),
        ),
        migrations.AlterField(
            model_name='googlecalendarwatch',
            name='resource_id',
            field=models.CharField(help_text='Google Calendar resource ID (calendar identifier)', max_length=255),
        ),
        migrations.AlterField(
            model_name='googlecalendarwatch',
            name='user',
            field=models.ForeignKey(help_text='User whose calendar is being watched', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_watches', to=settings.AUTH_USER_MODEL),
        ),
    ]
