# Generated by Django 4.2.29 on 2026-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0013_callattempt_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('nou', 'Client nou'), ('existent', 'Client existent')], db_index=True, default='nou', help_text='Whether this is a new client (no prior history) or existing (prior orders/visits).', max_length=20),
        ),
    ]
