# Generated by Django 4.2.29 on 2026-06-03 07:30

from django.db import migrations

import voice.encryption


def encrypt_existing(apps, schema_editor):
    """Encrypt any pre-existing plaintext OAuth secrets in place.

    After the AlterField operations above, the historical model uses
    EncryptedTextField, so reading returns the (graceful) plaintext and saving
    re-writes it as ciphertext. No-op when there are no rows (e.g. dev/demo),
    so it does not require FIELD_ENCRYPTION_KEY unless data actually exists.
    """
    Cred = apps.get_model("voice", "GoogleOauthCredential")
    for cred in Cred.objects.all():
        cred.save(update_fields=["token", "refresh_token", "client_secret"])


def noop_reverse(apps, schema_editor):
    # Cannot recover plaintext on reverse; leave values encrypted.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0014_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="client_secret",
            field=voice.encryption.EncryptedTextField(
                help_text="OAuth client secret (encrypted at rest)"
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="refresh_token",
            field=voice.encryption.EncryptedTextField(
                help_text="OAuth refresh token (encrypted at rest)"
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="token",
            field=voice.encryption.EncryptedTextField(
                help_text="OAuth access token (encrypted at rest)"
            ),
        ),
        migrations.RunPython(encrypt_existing, noop_reverse),
    ]
