# Generated by Django 4.2.29 on 2026-06-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0014_client_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarwatch",
            name="token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Random per-watch secret. Inbound webhooks must present a matching X-Goog-Channel-Token; requests that don't match are rejected.",
                max_length=64,
            ),
        ),
    ]
