# Generated by Django 4.2.30 on 2026-06-03 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0015_encrypt_oauth_credentials"),
        ("voice", "0015_googlecalendarwatch_token"),
    ]

    operations = []
