# Generated by Django 4.2.30 on 2026-06-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0016_merge_20260603_1156"),
    ]

    operations = [
        migrations.CreateModel(
            name="MegaPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("PRE_CALL", "Pre-call"),
                            ("POST_CALL", "Post-call"),
                            ("LESSONS_DISTILL", "Lessons distill"),
                        ],
                        db_index=True,
                        help_text="Which assembler domain this template drives",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human label for this version", max_length=255),
                ),
                (
                    "meta_prompt",
                    models.TextField(
                        help_text="Instructions sent to Claude. Supports {placeholders} — see spec §4.6."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only one active version per domain at a time",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mega_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mega Prompt",
                "verbose_name_plural": "Mega Prompts",
                "ordering": ["domain", "-version"],
            },
        ),
        migrations.AddConstraint(
            model_name="megaprompt",
            constraint=models.UniqueConstraint(
                fields=("domain", "version"), name="megaprompt_unique_domain_version"
            ),
        ),
    ]
