# Generated by Django 4.2.29 on 2026-06-03 20:20

from django.db import migrations


def seed_scenarios(apps, schema_editor):
    Scenario = apps.get_model("voice", "Scenario")
    starter = [
        ("Discovery", "discovery", "First substantive conversation; explore needs and fit."),
        ("Follow-up", "follow-up", "Continuing an active deal; advance toward decision."),
        ("Closing", "closing", "Securing a commitment / signature."),
        ("Debrief", "debrief", "Post-meeting reflection / loss analysis."),
        ("Other", "other", "Catch-all when the above don't apply."),
    ]
    for name, slug, desc in starter:
        Scenario.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "description": desc, "is_active": True},
        )


def unseed_scenarios(apps, schema_editor):
    Scenario = apps.get_model("voice", "Scenario")
    Scenario.objects.filter(slug__in=["discovery", "follow-up", "closing", "debrief", "other"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0018_scenario'),
    ]

    operations = [
        migrations.RunPython(seed_scenarios, unseed_scenarios),
    ]
