# Generated by Django 4.2.29 on 2026-06-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0019_seed_scenarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="post_call_first_message_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="post_call_prompt_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="pre_call_first_message_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="pre_call_prompt_locked",
            field=models.BooleanField(
                default=False,
                help_text="True after a manual edit; assembler will skip this field on regen",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="Visit scenario type — drives mega-prompt question shaping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="voice.scenario",
            ),
        ),
    ]
