# Generated by Django 4.2.29 on 2026-06-03 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0021_client_lessons_learned'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('PRE_CALL', 'Pre-call'), ('POST_CALL', 'Post-call'), ('LESSONS_DISTILL', 'Lessons distill')], db_index=True, max_length=20)),
                ('triggered_by', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('END_OF_MEETING', 'End of meeting')], max_length=20)),
                ('context_bundle', models.JSONField(blank=True, default=dict)),
                ('claude_request', models.TextField(blank=True, default='')),
                ('claude_response', models.TextField(blank=True, default='')),
                ('parsed_outputs', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, help_text='Set for LESSONS_DISTILL; NULL for PRE_CALL/POST_CALL (reach via visit.client)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='voice.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_runs', to=settings.AUTH_USER_MODEL)),
                ('mega_prompt', models.ForeignKey(help_text='The exact MegaPrompt version that was used', on_delete=django.db.models.deletion.PROTECT, related_name='generation_runs', to='voice.megaprompt')),
                ('visit', models.ForeignKey(blank=True, help_text='Set for PRE_CALL/POST_CALL; NULL for LESSONS_DISTILL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='voice.visit')),
            ],
            options={
                'verbose_name': 'Generation Run',
                'verbose_name_plural': 'Generation Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
