# Generated by Django 4.2.29 on 2026-06-03 20:47

from django.db import migrations


def migrate_meta_prompts(apps, schema_editor):
    GlobalSettings = apps.get_model("voice", "GlobalSettings")
    MegaPrompt = apps.get_model("voice", "MegaPrompt")

    gs = GlobalSettings.objects.first()
    if gs is None:
        return

    pairs = (
        ("PRE_CALL", "pre_call_meta_prompt"),
        ("POST_CALL", "post_call_meta_prompt"),
    )
    for domain, field in pairs:
        existing_active = MegaPrompt.objects.filter(domain=domain, is_active=True).first()
        if existing_active:
            continue
        value = (getattr(gs, field, None) or "").strip()
        if not value:
            # The seed file already provides a starter; leave the row to be created by seed_mega_prompts.
            continue
        MegaPrompt.objects.create(
            domain=domain,
            name=f"Migrated from GlobalSettings.{field}",
            meta_prompt=value,
            is_active=True,
            version=1,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0023_globalsettings_max_context_tokens_warn"),
    ]

    operations = [
        migrations.RunPython(migrate_meta_prompts, noop_reverse),
    ]
