# Generated by Django 4.2.29 on 2026-06-03 20:53

from pathlib import Path

from django.db import migrations
from django.db.models import Max

# Resolve seed-file dir relative to this migration's location.
# This file lives at voice/migrations/0025_*.py.
# Seed files live at voice/management/commands/seed_data/mega_prompts/.
SEED_DIR = (
    Path(__file__).resolve().parent.parent
    / "management"
    / "commands"
    / "seed_data"
    / "mega_prompts"
)

DOMAIN_TO_FILENAME = {
    "PRE_CALL": "pre_call.txt",
    "POST_CALL": "post_call.txt",
    "LESSONS_DISTILL": "lessons_distill.txt",
}


def seed_megaprompts_from_files(apps, schema_editor):
    """For each domain still without an active MegaPrompt, create one from its seed file.

    Runs after 0024_migrate_globalsettings_to_megaprompt — which may already have
    created PRE_CALL/POST_CALL rows from legacy GlobalSettings content. This step
    fills any remaining gaps so every domain has an active row after `migrate`,
    with no manual `seed_mega_prompts` command needed.

    Version assignment mirrors the seed_mega_prompts command: max(version)+1 per domain,
    so we don't clash with any prior (inactive) versions that might already exist.
    """
    MegaPrompt = apps.get_model("voice", "MegaPrompt")

    for domain, filename in DOMAIN_TO_FILENAME.items():
        if MegaPrompt.objects.filter(domain=domain, is_active=True).exists():
            continue

        seed_path = SEED_DIR / filename
        if not seed_path.exists():
            # Should not happen in a normal deploy (seed files are committed),
            # but skip rather than raise so a partial deploy can still proceed.
            continue

        content = seed_path.read_text(encoding="utf-8")
        if not content.strip():
            continue

        max_v = (
            MegaPrompt.objects.filter(domain=domain).aggregate(Max("version"))["version__max"] or 0
        )
        new_version = max_v + 1

        MegaPrompt.objects.create(
            domain=domain,
            name=f"Seeded v{new_version} (from seed file)",
            meta_prompt=content,
            is_active=True,
            version=new_version,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0024_migrate_globalsettings_to_megaprompt"),
    ]

    operations = [
        migrations.RunPython(seed_megaprompts_from_files, noop_reverse),
    ]
