# Generated by Django 4.2.29 on 2026-06-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0025_seed_megaprompts_from_files"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="megaprompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("domain",),
                name="megaprompt_one_active_per_domain",
            ),
        ),
    ]
