# Generated by Django 4.2.29 on 2026-06-03 21:04

from django.db import migrations

import voice.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0026_megaprompt_megaprompt_one_active_per_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationrun",
            name="claude_request",
            field=voice.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="generationrun",
            name="claude_response",
            field=voice.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="generationrun",
            name="context_bundle",
            field=voice.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="generationrun",
            name="error",
            field=voice.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="generationrun",
            name="parsed_outputs",
            field=voice.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
    ]
