# Generated by Django 4.2.29 on 2026-06-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0027_alter_generationrun_claude_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationrun",
            name="mega_prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="The exact MegaPrompt version that was used; NULL when the assembler failed before a MegaPrompt could be loaded (e.g. no active version exists for the domain).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generation_runs",
                to="voice.megaprompt",
            ),
        ),
    ]
