# Generated by Django 4.2.30 on 2026-06-03 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0028_alter_generationrun_mega_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="post_call_meta_prompt",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="pre_call_meta_prompt",
        ),
    ]
