# Generated by Django 4.2.30 on 2026-06-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0034_repair_cross_agent_visit_mislinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="methodology",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="callattempt",
            index=models.Index(fields=["visit"], name="voice_calla_visit_idx"),
        ),
        migrations.AddIndex(
            model_name="callattempt",
            index=models.Index(fields=["visit", "phase"], name="voice_calla_visit_phase_idx"),
        ),
        migrations.AddIndex(
            model_name="generationrun",
            index=models.Index(fields=["visit"], name="voice_genrun_visit_idx"),
        ),
        migrations.AddIndex(
            model_name="generationrun",
            index=models.Index(fields=["domain", "success"], name="voice_genrun_domsucc_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["client"], name="voice_visit_client_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["agent", "status"], name="voice_visit_agent_status_idx"),
        ),
    ]
