# Generated by Django 4.2.29 on 2026-06-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0035_add_perf_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="agent",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="voice_activ_meeting_ae0b40_idx",
        ),
        migrations.RemoveIndex(
            model_name="callattempt",
            name="voice_calla_meeting_735910_idx",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="callattempt",
            name="meeting",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated visit (nullable for user-level / global events)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="voice.visit",
            ),
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
    ]
